Feature pygithub api integration
fga-gpp-mds/2018.1-Grupo2 pull request #69
Opened 2018-04-02 04:35 UTC by Mateusas3s

### Description
PyGithub API tutorial document added.

### Types of change (Check "x")
- [ ] Bug fix
- [ ] New Feature
- [x] Documentation

### Related Issue
Fix #34

2018-04-02 11:19 UTC, lucasca73 requested changes
A chave de uso da api não pode estar pública. No arquivo: pygithub_api_integration/views.py
A chave da API deve estar em um arquivo local.

Chave de API, emails, logins e senhas, públicas, gera risco de segurança.

2018-04-02 11:40 UTC, Mateusas3s commented
Ok, farei as alterações mais tarde

2018-04-02 11:46 UTC, lucasca73 commented
Também tem que adicionar o arquivo no gitignore.

2018-04-03 17:30 UTC, lucasca73 commented
@Mateusas3s 

Nesse post da um exemplo sobre guardar segredos em arquivo e importar o dados na aplicação. É o mais simples que encontrei.
https://gist.github.com/M0nica

É normal que coloquem segredos num arquivo chamado "environment" que é responsável por guardar as variáveis de ambiente da aplicação, que não podem ser publicamente colocadas.
https://godjango.com/blog/working-with-environment-variables-in-python/

* vou criar uma issue para atualizar o readme explicando que a aplicação necessita desse arquivo.

2018-04-04 14:55 UTC, lucasca73 commented
@Mateusas3s há alguns conflitos nos arquivos.

2018-04-05 04:17 UTC, lucasca73 approved these changes

2018-04-05 04:17 UTC, merged